# Generated by Django 6.0.3 on 2026-03-30 07:52

import apps.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('phone_numbers', models.CharField(blank=True, max_length=200)),
                ('office_address', models.TextField(blank=True)),
                ('meta_title', models.JSONField(default=apps.integrations.models.translated_default)),
                ('meta_description', models.JSONField(default=apps.integrations.models.translated_default)),
                ('holiday_mode', models.BooleanField(default=False)),
                ('holiday_message', models.JSONField(default=apps.integrations.models.translated_default)),
                ('active_translation_engine', models.CharField(choices=[('lovable', 'Lovable AI'), ('deepl', 'DeepL'), ('google', 'Google Translate')], default='lovable', max_length=30)),
                ('deepl_api_key', models.CharField(blank=True, max_length=200)),
                ('google_translate_key', models.CharField(blank=True, max_length=200)),
                ('calendly_url', models.URLField(blank=True)),
                ('zoom_url', models.URLField(blank=True)),
                ('primary_meeting_method', models.CharField(choices=[('calendly', 'Calendly'), ('zoom', 'Zoom')], default='calendly', max_length=10)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
