# Generated by Django 6.0.3 on 2026-03-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='active_translation_engine',
            field=models.CharField(choices=[('google_free', 'Google Translate (Free)'), ('deepl', 'DeepL'), ('google_translate', 'Google Translate API'), ('none', 'None')], default='google_free', max_length=30),
        ),
    ]
