# Generated by Django 6.0.3 on 2026-03-30 07:52

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=apps.content.models.translated_default)),
                ('subtitle', models.JSONField(default=apps.content.models.translated_default)),
                ('button_text', models.JSONField(default=apps.content.models.translated_default)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('button_link', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('transactional', 'Transactional'), ('notification', 'Notification'), ('marketing', 'Marketing')], max_length=20)),
                ('subject', models.JSONField(default=apps.content.models.translated_default)),
                ('body', models.JSONField(default=apps.content.models.translated_default)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.JSONField(default=apps.content.models.translated_default)),
                ('content', models.JSONField(default=apps.content.models.translated_default)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
