# Generated by Django 6.0.3 on 2026-03-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='browser_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
