# Generated by Django 6.0.3 on 2026-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_browser_language_lead_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('standard', 'Standard Quote'), ('custom', 'Custom Development')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_material',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='reference_image',
            field=models.FileField(blank=True, null=True, upload_to='custom-requests/'),
        ),
    ]
