# Generated by Django 6.0.3 on 2026-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_lead_type_lead_preferred_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to='leads/logos/'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reference_image',
            field=models.FileField(blank=True, null=True, upload_to='leads/references/'),
        ),
    ]
