# Generated by Django 6.0.3 on 2026-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
