# Generated by Django 6.0.3 on 2026-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediafile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='alt_text',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
