# Generated by Django 6.0.3 on 2026-03-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('unique_visits', models.IntegerField(default=0)),
                ('total_hits', models.IntegerField(default=0)),
                ('top_country', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_hash', 'path', 'visited_at'], name='analytics_p_ip_hash_b844e1_idx'), models.Index(fields=['country'], name='analytics_p_country_dd95e0_idx')],
            },
        ),
    ]
