# Generated by Django 6.0.3 on 2026-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_materials',
            field=models.JSONField(default=list, help_text='List of available materials: cowhide, buffalo, pu, pvc'),
        ),
    ]
